name: CI

on:
  push:
    branches: [main]
    paths:
      - 'NodeJs/RENTALX/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node_version: 14.x
      
      - name: Build
        run: yarn build
      
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules"
          target: "test"
